### ISSUE TITLE
Чек лабы 1

### ISSUE THREAD

**Issue by H30H** [palmaus/Sem3-Lab1#1]
- [x] Дублирование указателя на данные в `control_block` и `SharedPtr`, выбери только одно место, где его хранить
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/SharedPtr.h#L14
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/SharedPtr.h#L112-L113

- [x] Такая реализация decrement провоцирует утечку памяти, тк ты нигде не удаляешь динмическую память `controlBlock`
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/SharedPtr.h#L126-L132

- [x] В `UniquePtr` ты проверял на `ptr == nullptr`, а тут забыл + 2 версии для `const` и `не const`
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/SharedPtr.h#L74-L77

- [x] Вот тут я бы кидал исключение, а не создавал указатель на `nullptr`
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/WeakPtr.h#L50-L55

- [x] Также надо 2 версии `const` и `не const`
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/LinkedList.h#L78-L99

- [x] Вот такие `if` .. `else if` ... `else if` ... `else`, после которых никакого общего кода нет, можно более красиво переписать на: `if` ... `return;` `if` ... `return;` ... и вместо последнего `else` ничего писать не надо. Получится примерно так:

`до`
if (some1)
  do_some1()
else if (some2)
  do_some2()
else if (some3)
  do_some3()
...
else
  do_some_n()

`после`
if (some1)
  do_some1()
  return;

if (some2)
  do_some2()
  return;

if (some3)
  do_some3()
  return;
...
do_some_n()

https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/LinkedList.h#L154-L158
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/LinkedList.h#L176-L192

- [x] По заданию надо было переписать какой-нибудь из методов в `Sequence` на умные указатели, в твоём случае тебе ещё надо обновить их аналоги в `LinkedList`:
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/MutableSequence.h#L25
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/MutableSequence.h#L33

- [x] Мне не нравиться ненужное копирование листа на ровном месте, те ты получил указатель на результат, скопировал его в новый `Sequence`, а затем удалил, когда можно было сразу без копирования создать `Sequence`
https://github.com/palmaus/Sem3-Lab1/blob/9091dced16c47da6d97b749822130ef1cb695589/include/project/MutableListSequence.h#L29-L34

- [x] По поводу бенчмарков, интереснее наблюдать не за распределением на 1М итерациях, а за сразу за несколькими непрерывными графиками, например, от 10к до 1М итераций с шагом 10к (те 100 точек для каждой линии) на одном графике сразу. По одной фиксированной точке ничего не понятно, если в след лабе будешь делать подобное, то поймёшь

**Comment by palmaus** [comment]
Вроде всё исправил
